// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc.proto
// Protobuf Java Version: 4.26.0

package com.repcomm.sneknet.protos;

public final class IPC {
  private IPC() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "",
      IPC.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ipc_IPv4Info_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ipc_IPv4Info_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ipc_IPv4TcpMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ipc_IPv4TcpMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ipc_IPv4UdpMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ipc_IPv4UdpMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ipc_IpcMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ipc_IpcMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tipc.proto\022\003ipc\",\n\010IPv4Info\022\017\n\007SrcIPv4\030" +
      "\001 \001(\005\022\017\n\007DstIPv4\030\002 \001(\005\"\211\001\n\nIPv4TcpMsg\022\017\n" +
      "\007SrcPort\030\001 \001(\005\022\017\n\007DstPort\030\002 \001(\005\022\033\n\004IPv4\030" +
      "\003 \001(\0132\r.ipc.IPv4Info\022\r\n\005IsSyn\030\004 \001(\010\022\r\n\005I" +
      "sAck\030\005 \001(\010\022\r\n\005SeqId\030\006 \001(\r\022\017\n\007Payload\030\007 \001" +
      "(\014\"\\\n\nIPv4UdpMsg\022\017\n\007SrcPort\030\001 \001(\005\022\017\n\007Dst" +
      "Port\030\002 \001(\005\022\033\n\004IPv4\030\003 \001(\0132\r.ipc.IPv4Info\022" +
      "\017\n\007Payload\030\004 \001(\014\"\336\001\n\006IpcMsg\022\025\n\rTransacti" +
      "onId\030\001 \001(\005\022\027\n\nIsResponse\030\002 \001(\010H\001\210\001\001\022\026\n\tI" +
      "sSuccess\030\003 \001(\010H\002\210\001\001\022\022\n\005Error\030\004 \001(\tH\003\210\001\001\022" +
      "\"\n\007IPv4Tcp\030\005 \001(\0132\017.ipc.IPv4TcpMsgH\000\022\"\n\007I" +
      "Pv4Udp\030\006 \001(\0132\017.ipc.IPv4UdpMsgH\000B\t\n\007paylo" +
      "adB\r\n\013_IsResponseB\014\n\n_IsSuccessB\010\n\006_Erro" +
      "rB2\n\032com.repcomm.sneknet.protosB\003IPCP\001Z\r" +
      "common/protosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ipc_IPv4Info_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ipc_IPv4Info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ipc_IPv4Info_descriptor,
        new java.lang.String[] { "SrcIPv4", "DstIPv4", });
    internal_static_ipc_IPv4TcpMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ipc_IPv4TcpMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ipc_IPv4TcpMsg_descriptor,
        new java.lang.String[] { "SrcPort", "DstPort", "IPv4", "IsSyn", "IsAck", "SeqId", "Payload", });
    internal_static_ipc_IPv4UdpMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ipc_IPv4UdpMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ipc_IPv4UdpMsg_descriptor,
        new java.lang.String[] { "SrcPort", "DstPort", "IPv4", "Payload", });
    internal_static_ipc_IpcMsg_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ipc_IpcMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ipc_IpcMsg_descriptor,
        new java.lang.String[] { "TransactionId", "IsResponse", "IsSuccess", "Error", "IPv4Tcp", "IPv4Udp", "Payload", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
