// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc.proto

// Protobuf Java Version: 4.26.0
package com.repcomm.sneknet.protos;

public interface IPv4InfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ipc.IPv4Info)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 SrcIPv4 = 1;</code>
   * @return The srcIPv4.
   */
  int getSrcIPv4();

  /**
   * <code>int32 DstIPv4 = 2;</code>
   * @return The dstIPv4.
   */
  int getDstIPv4();
}
