// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc.proto

// Protobuf Java Version: 4.26.0
package com.repcomm.sneknet.protos;

public interface IPv4TcpMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ipc.IPv4TcpMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 SrcPort = 1;</code>
   * @return The srcPort.
   */
  int getSrcPort();

  /**
   * <code>int32 DstPort = 2;</code>
   * @return The dstPort.
   */
  int getDstPort();

  /**
   * <code>.ipc.IPv4Info IPv4 = 3;</code>
   * @return Whether the iPv4 field is set.
   */
  boolean hasIPv4();
  /**
   * <code>.ipc.IPv4Info IPv4 = 3;</code>
   * @return The iPv4.
   */
  com.repcomm.sneknet.protos.IPv4Info getIPv4();
  /**
   * <code>.ipc.IPv4Info IPv4 = 3;</code>
   */
  com.repcomm.sneknet.protos.IPv4InfoOrBuilder getIPv4OrBuilder();

  /**
   * <code>bool IsSyn = 4;</code>
   * @return The isSyn.
   */
  boolean getIsSyn();

  /**
   * <code>bool IsAck = 5;</code>
   * @return The isAck.
   */
  boolean getIsAck();

  /**
   * <code>uint32 SeqId = 6;</code>
   * @return The seqId.
   */
  int getSeqId();

  /**
   * <code>bytes Payload = 7;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();
}
